---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wavefront-proxy
    name: wavefront-proxy
  name: wavefront-proxy
  namespace: wavefront-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wavefront-proxy
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: wavefront-proxy
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - wavefront-proxy
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: wavefront-proxy
        image: wavefronthq/proxy:12.3
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        envFrom:
        - secretRef:
            name: wavefront-token
        env:
        - name: WAVEFRONT_URL
          value: https://binz.wavefront.com/api
        - name: WAVEFRONT_PROXY_ARGS
          value: --preprocessorConfigFile /preprocessor-config/preprocessor_rules.yaml
        ports:
        - containerPort: 2878
          protocol: TCP
        volumeMounts:
        - name: proxy-preprocessor-config
          mountPath: /preprocessor-config/
          readOnly: true
        securityContext:
          privileged: false
      volumes:
      - name: proxy-preprocessor-config
        configMap:
          name: proxy-preprocessor-config
---
apiVersion: v1
kind: Service
metadata:
  name: wavefront-proxy
  labels:
    app: wavefront-proxy
  namespace: wavefront-system
spec:
  type: LoadBalancer
  ports:
  - name: wavefront
    port: 2878
    protocol: TCP
  selector:
    app: wavefront-proxy
